ARG POSTGRES_VERSION=16
FROM postgres:${POSTGRES_VERSION}

# Install OpenSSL and sudo
RUN apt-get update && apt-get install -y openssl sudo

# Allow the postgres user to execute certain commands as root without a password
RUN echo "postgres ALL=(root) NOPASSWD: /usr/bin/mkdir, /bin/chown, /usr/bin/openssl" > /etc/sudoers.d/postgres

# Add init scripts while setting permissions
COPY --chmod=755 init-ssl.sh /docker-entrypoint-initdb.d/init-ssl.sh
COPY --chmod=755 init-realtime.sh /docker-entrypoint-initdb.d/init-realtime.sh
COPY --chmod=755 wrapper.sh /usr/local/bin/wrapper.sh

ENTRYPOINT ["wrapper.sh"]
# Set the command with the same postgres configuration
CMD ["postgres", \
     "--port=5432", \
     "-c", "wal_level=logical", \
     "-c", "max_replication_slots=10", \
     "-c", "max_wal_senders=10"]
